backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: single_file

  # Required - a list of locales to show in the editor UI
  locales: [en, it, fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
  - name: "pages"
    label: "Pages"
    i18n:
      structure: single_file
    files:
      - label: "HomePage"
        name: "homepage"
        file: "src/pages/files/homepage.yml"
        i18n: true
        fields:
          - { label: Hero Title, name: hero_title, widget: string, i18n: true }
          - label: "Mission"
            name: "mision"
            widget: "relation"
            collection: "mission"
            searchFields: mision
            valueField: mision
      - label: "About Page"
        name: "about"
        file: "src/pages/files/about.yml"
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
          - { label: Intro, name: intro, widget: markdown, i18n: true }
          - label: Image
            name: image
            widget: image

  - name: mission
    label: Mission
    delete: false
    i18n:
      structure: single_file
    files:
      - name: "mission"
        label: "Mission"
        file: "src/pages/files/mission.yml"
        description: "Our Mission"
        i18n: true
        fields:
          - label: Title
            name: title
            widget: string
            i18n: true
          - label: Subtitle
            name: subtitle
            widget: string
            i18n: true
          - label: body
            name: body
            widget: markdown
            i18n: true
          - label: Image
            name: image
            widget: image

  - name: "posts"
    label: "Projects"
    folder: "src/pages/posts"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: Author
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"
